spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    database: POSTGRESQL
    show-sql: false

  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/holiday
    username: postgres
    password: postgres

services:
  mailgun:
    host: smtp.mailgun.org
    username:
    password:

app.security.jwt:
  tokenExpirationTime: 15 # Minutes
  refreshTokenExpTime: 60 # Minutes
  tokenSigningKey: dummy
