server:
  port: 5000

spring:
  jpa:
    hibernate:
      ddl-auto: create
    database: POSTGRESQL
    show-sql: false

  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/holiday
    username: postgres
    password: postgres

services:
  mailgun:
    host: smtp.mailgun.org
    username: postmaster@email.chll.cz
    password: u+7Y;c?3+vn7tDq4
    defaulAlias: chllbot
    defaultFrom: chll@email.chll.cz

app:
  allowedOrigin: http://localhost:3000
  security.jwt:
    tokenExpirationTime: 15 # Minutes
    refreshTokenExpTime: 60 # Minutes
    tokenSigningKey: dummy
