spring:
  jpa:
    hibernate:
      ddl-auto: create
    database: POSTGRESQL
    show-sql: false

  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/holiday
    username: postgres
    password: postgres

services:
  mailgun:
    host: smtp.mailgun.org
    username: postmaster@sandboxbb6129ee545e47a683cecce938eb51a5.mailgun.org
    password: ahojahoj

app.security.jwt:
  tokenExpirationTime: 15 # Minutes
  refreshTokenExpTime: 60 # Minutes
  tokenSigningKey: dummy
