version: 2

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: gradle:latest
      - image: postgres:latest
        env:
         - POSTGRES_DB=holiday
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "build.gradle" }}

      - run:
          name: update-desp
          command: './gradlew test build'
